name: Call Reusable Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: nushankodikara/reusable-workflows/.github/workflows/docker-publish.yaml@main
    with:
      docker_image_and_tag: your-dockerhub-username/your-image-name:latest
      docker_username: your-dockerhub-username
      context: .
      dockerfile: ./Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 