name: Reusable - Build and Push Docker Image

on:
  workflow_call:
    inputs:
      docker_image_and_tag:
        description: 'The Docker image name and tag (e.g., my-org/my-image:latest)'
        required: true
        type: string
      docker_username:
        description: 'DockerHub username'
        required: true
        type: string
      context:
        description: 'The build context path.'
        required: false
        type: string
        default: '.'
      dockerfile:
        description: 'Path to the Dockerfile.'
        required: false
        type: string
        default: './Dockerfile'
      platforms:
        description: 'Target platforms for the Docker build, comma-separated.'
        required: false
        type: string
        default: 'linux/amd64,linux/arm64/v8'
    secrets:
      DOCKERHUB_TOKEN:
        description: 'DockerHub token with write access to the repository'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ inputs.docker_image_and_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max